#!/bin/bash
yum update -y,
sudo yum install httpd -y,
sudo service httpd start,
sudo chkconfig httpd on,
sudo echo "HELLO WORLD" > /var/www/html/index.html,
sudo echo "HELLO WORLD from $(hostname -f)" > /var/www/html/index.html
